name: LLMChat
options:
  bundleIdPrefix: com.$(DEVELOPMENT_TEAM)
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  swift: "6.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
    PRODUCT_BUNDLE_IDENTIFIER: com.$(DEVELOPMENT_TEAM).llmchat
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  LLMChat:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_NAME: LLMChat
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    entitlements:
      path: LLMChat.entitlements
      properties:
        com.apple.developer.foundation-models.inference: true
