name: LLMChat
options:
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  swift: "6.0"

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    DEVELOPMENT_TEAM: ${DEVELOPMENT_TEAM}
    PRODUCT_BUNDLE_IDENTIFIER: ${APP_IDENTIFIER}
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  LLMChat:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - Sources
      - Resources/Assets.xcassets
    settings:
      base:
        PRODUCT_NAME: LLMChat
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
    dependencies:
      - sdk: ImagePlayground.framework
        embed: false
    entitlements:
      path: LLMChat.entitlements
